name: Validate Renovate config

on:
  push:
    branches:
      - main
    paths:
      - 'renovate-config.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'renovate-config.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate Renovate config
        run: docker run --rm -v "$PWD/renovate-config.json:/tmp/renovate-config.json" ghcr.io/renovatebot/renovate:43.195.1 renovate-config-validator /tmp/renovate-config.json
